# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 048589f3056b60d4c8e185b7d83e4fc84790e55e8ee5a684c47cc132a7a05b6cb7e80d72444f2bb911f97123b696a8a3e49bcbcb675d373a7c759e8c14df49de

test:
  secret_key_base: fb91165d53de4781d9853ddfe6da7a71d008181413de69734939c243a997f2fd89c89da5ec6b9db878b339d8071cf7456651cb53b7df2cdbfd54ee5189bd109a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
